# Generated by Django 3.1.2 on 2020-11-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='history',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='construction',
            name='creation_date',
            field=models.DateField(),
        ),
    ]
